target_type: 'aprilgrid' #gridtype
tagCols: 6               #number of apriltags
tagRows: 6               #number of apriltags
tagSize: 0.0246          #size of apriltag, edge to edge [m]
tagSpacing: 0.3          #ratio of space between tags to tagSize

