name: Docker Image CI

on:
  push:
    branches: [ 'master', 'develop' ]
  pull_request:
    branches: [ 'master', 'develop' ]

jobs:

  build-kinetic:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build code for Ubuntu 16
      run: docker build . -f ./scripts/docker/astrobee_kinetic.Dockerfile -t astrobee/astrobee:latest-kinetic

    - name: Test code
      run: |
        sudo apt-get install python3-rocker
        rocker --nvidia --x11 astrobee/astrobee:latest-kinetic /astrobee_init.sh rostest choreographer test_zones_nominal.test

  build-melodic:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build code for Ubuntu 18
      run: docker build . -f ./scripts/docker/astrobee_melodic.Dockerfile -t astrobee/astrobee:latest-melodic

    - name: Test code
      run: docker build . -f ./scripts/docker/test_astrobee_melodic.Dockerfile -t test