name: Build and Test CI for Pull Requests

on:
  pull_request:
    branches: [ 'master', 'develop' ]

jobs:

  build-xenial:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build code for Ubuntu 16
      run: docker build . -f ./scripts/docker/astrobee.Dockerfile
                          --build-arg UBUNTU_VERSION=16.04
                          --build-arg ROS_VERSION=kinetic
                          --build-arg PYTHON=''
                          --build-arg REMOTE=ghcr.io/nasa
                          -t astrobee/astrobee:latest-ubuntu16.04

    - name: Test code
      run: docker build . -f ./scripts/docker/test_astrobee.Dockerfile
                          --build-arg UBUNTU_VERSION=16.04
                          -t astrobee/astrobee:test-ubuntu16.04

  build-bionic:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build code for Ubuntu 18
      run: docker build . -f ./scripts/docker/astrobee.Dockerfile
                          --build-arg UBUNTU_VERSION=18.04
                          --build-arg ROS_VERSION=melodic
                          --build-arg PYTHON=3
                          --build-arg REMOTE=ghcr.io/nasa
                          -t astrobee/astrobee:latest-ubuntu18.04

    - name: Test code
      run: docker build . -f ./scripts/docker/test_astrobee.Dockerfile
                          --build-arg UBUNTU_VERSION=18.04
                          -t astrobee/astrobee:test-ubuntu18.04

  build-focal:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Build code for Ubuntu 20
      run: docker build . -f ./scripts/docker/astrobee.Dockerfile
                          --build-arg UBUNTU_VERSION=20.04
                          --build-arg ROS_VERSION=noetic
                          --build-arg PYTHON=3
                          --build-arg REMOTE=ghcr.io/nasa
                          -t astrobee/astrobee:latest-ubuntu20.04

    - name: Test code
      run: docker build . -f ./scripts/docker/test_astrobee.Dockerfile
                          --build-arg UBUNTU_VERSION=20.04
                          -t astrobee/astrobee:test-ubuntu20.04
