name: Build, test and push packages CI

on:
  push:
    branches-ignore:
      - gh-pages
      - ros2

jobs:

  build-xenial:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build, test, push docker
      run: >
        revision="latest";
        build_arg="astrobee";
        push_arg="";
        branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}};
        if [ "${{ github.repository_owner }}" == "nasa" ]; then
          if [ $branch == "develop" ]; then
            push_arg="push_astrobee";
          fi;
          if [ $branch == "master" ]; then
            export VERSION=`grep -w -m 1 "Release" RELEASE.md | awk '{print $3}'`;
            revision="v${VERSION}";
            build_arg="astrobee_base astrobee";
            push_arg="push_astrobee_base push_astrobee";
          fi;
        fi;
        command="./scripts/docker/build.sh --xenial --remote --revision ${revision} \
                                     --owner ${{ github.repository_owner }} \
                                     ${build_arg} test_astrobee ${push_arg}";
        echo "$command";
        eval "$command";

  build-bionic:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build, test, push docker
      run: >
        revision="latest";
        build_arg="astrobee";
        push_arg="";
        branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}};
        if [ "${{ github.repository_owner }}" == "nasa" ]; then
          if [ $branch == "develop" ]; then
            push_arg="push_astrobee";
          fi;
          if [ $branch == "master" ]; then
            export VERSION=`grep -w -m 1 "Release" RELEASE.md | awk '{print $3}'`;
            revision="v${VERSION}";
            build_arg="astrobee_base astrobee";
            push_arg="push_astrobee_base push_astrobee";
          fi;
        fi;
        command="./scripts/docker/build.sh --bionic --remote --revision ${revision} \
                                     --owner ${{ github.repository_owner }} \
                                     ${build_arg} test_astrobee ${push_arg}";
        echo "$command";
        eval "$command";

  build-focal:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build, test, push docker
      run: >
        revision="latest";
        build_arg="astrobee";
        push_arg="";
        branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}};
        if [ "${{ github.repository_owner }}" == "nasa" ]; then
          if [ $branch == "develop" ]; then
            push_arg="push_astrobee";
          fi;
          if [ $branch == "master" ]; then
            export VERSION=`grep -w -m 1 "Release" RELEASE.md | awk '{print $3}'`;
            revision="v${VERSION}";
            build_arg="astrobee_base astrobee";
            push_arg="push_astrobee_base push_astrobee";
          fi;
        fi;
        command="./scripts/docker/build.sh --focal --remote --revision ${revision} \
                                     --owner ${{ github.repository_owner }} \
                                     ${build_arg} test_astrobee ${push_arg}";
        echo "$command";
        eval "$command";