name: Build, test and push packages CI

on:
  push:
    branches: [ 'release' ]

jobs:

  build-xenial:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build, test, push base docker
      run: ./scripts/docker/build.sh --xenial
                                     --owner ${{ github.repository_owner }}
				     astrobee_base astrobee test_astrobee
				     push_astrobee_base

    - name: Push code docker
      run: |
        export VERSION=`grep -w -m 1 "Release" RELEASE.md | awk '{print $3}'`
	docker tag astrobee/astrobee:latest-ubuntu16.04 ghcr.io/${{ github.repository_owner }}/astrobee:v${VERSION}-ubuntu16.04
        docker push ghcr.io/${{ github.repository_owner }}/astrobee:v${VERSION}-ubuntu16.04

  build-bionic:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build, test, push base docker
      run: ./scripts/docker/build.sh --bionic
                                     --owner ${{ github.repository_owner }}
				     astrobee_base astrobee test_astrobee
				     push_astrobee_base

    - name: Push code docker
      run: |
        export VERSION=`grep -w -m 1 "Release" RELEASE.md | awk '{print $3}'`
	docker tag astrobee/astrobee:latest-ubuntu18.04 ghcr.io/${{ github.repository_owner }}/astrobee:v${VERSION}-ubuntu18.04
        docker push ghcr.io/${{ github.repository_owner }}/astrobee:v${VERSION}-ubuntu18.04

  build-focal:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodule
      run: git submodule update --init --depth 1 description/media

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Build, test, push base docker
      run: ./scripts/docker/build.sh --focal
                                     --owner ${{ github.repository_owner }}
				     astrobee_base astrobee test_astrobee
				     push_astrobee_base

    - name: Push code docker
      run: |
        export VERSION=`grep -w -m 1 "Release" RELEASE.md | awk '{print $3}'`
	docker tag astrobee/astrobee:latest-ubuntu20.04 ghcr.io/${{ github.repository_owner }}/astrobee:v${VERSION}-ubuntu20.04
        docker push ghcr.io/${{ github.repository_owner }}/astrobee:v${VERSION}-ubuntu20.04
